### ISSUE TITLE
The data on NFT-related pages is abnormal.

### ISSUE THREAD

**Issue by FrederLu** [Magickbase/ckb-explorer-public-issues#338]
1、The NFT of cota type is on the transaction details page,`
Detail` should display the corresponding icon (refer to https://github.com/nervosnetwork/ckb-explorer-frontend/pull/1093).
 https://pudge.explorer.nervos.org/nft-collections/18188
https://pudge.explorer.nervos.org/transaction/0x98603bce628d7771d73d8a0e109b941be6c952985d2e0a44cfd306b57afb0e0f
<img width="1299" alt="image" src="https://github.com/Magickbase/ckb-explorer-public-issues/assets/25676576/293e7b9e-47c1-42dd-9edb-c55b3447e7ec">

---
2、The `Action` of the NFT is displayed incorrectly.
https://pudge.explorer.nervos.org/nft-collections/18072
<img width="1289" alt="image" src="https://github.com/Magickbase/ckb-explorer-public-issues/assets/25676576/244b3956-004a-45d4-80c4-53f33174099f">

https://pudge.explorer.nervos.org/nft-info/18072/50
<img width="1173" alt="image" src="https://github.com/Magickbase/ckb-explorer-public-issues/assets/25676576/3c33f5e4-f60a-45b2-8792-81ea70342c6d">

**Comment by rabbitz** [comment]
Related issue: https://github.com/Magickbase/ckb-explorer-public-issues/issues/340

**Comment by rabbitz** [comment]
1. cota type error reason:

https://github.com/nervosnetwork/ckb-explorer/blob/develop/app/utils/ckb_utils.rb#L378
The cell_type here does not handle the cota type, resulting in the corresponding cota type cell being unable to be parsed correctly, and the default type `normal` is stored.

2. token transfer action error reason:

This record was created on Thu, 01 Dec 2022 10:59:21 At this time, the parsed transaction type field is `type`, but actually this field should be `tx_type`, and the `tx_type` type modification time is Dec 21, 2022 https://github.com/nervosnetwork/ckb-explorer/commit/9cf9c5883a49a3fbfcf5d6f1e65553b41a21bceb

```bash
echo '{
    "id":2,
    "jsonrpc":"2.0",
    "method":"get_transactions_by_block_number",
    "params":{
        "block_number": "7525071"
    }
}' \
| tr -d '\n' \
| curl -H 'content-type: application/json' -d @- \
https://cota.nervina.dev/aggregator

{
  "jsonrpc": "2.0",
  "result": {
    "block_number": 9557050,
    "transactions": [
      {
        "block_number": 7525071,
        "cota_id": "0x28496dbb4649c7c4109ce5998c4f007e1b797cb6",
        "from": "ckt1qzda0cr08m85hc8jlnfp3zer7xulejywt49kt2rr0vthywaa50xwsqtjlt2d6ghrpwqhlre8twvxxgwrmpx22ps2cpefm",
        "to": "ckt1qzda0cr08m85hc8jlnfp3zer7xulejywt49kt2rr0vthywaa50xwsqtjlt2d6ghrpwqhlre8twvxxgwrmpx22ps2cpefm",
        "token_index": "0x00000032",
        "tx_hash": "0x220bed8a1d2e574475f6376016e12f9b167afdebae624470e0686289f2831ba2",
        "tx_type": "mint"
      }
    ]
  },
  "id": 2
}
```

**Comment by rabbitz** [comment]
Related pull request

https://github.com/nervosnetwork/ckb-explorer/pull/1303

**Comment by rabbitz** [comment]
The cota type error on testnet has been fixed, and the Detail can now display the correct cota type icon.

@FrederLu

**Comment by FrederLu** [comment]
> The cota type error on testnet has been fixed, and the Detail can now display the correct cota type icon.
> 
> @FrederLu

Icons of cota type are now displayed normally. But the second problem seems to still exist, is it necessary to wait for data processing?

**Comment by rabbitz** [comment]
> > The cota type error on testnet has been fixed, and the Detail can now display the correct cota type icon.
> > @FrederLu
> 
> Icons of cota type are now displayed normally. But the second problem seems to still exist, is it necessary to wait for data processing?

The second problem on testnet has been fixed.

**Comment by FrederLu** [comment]
Verified.
